print("When did Flynn go to the dentist")
input("")
print("At 2-00th-30")
print("What do you call cheese that isn't yours")
input("")
print("Na-cho-cheese")
print("What do you call a band with killer whales") 
input("")
print("An orcha-stra")
print("Why don't seagulls fly over the bay")
input("")
print("Because then they'd be bagels")
print("Why did the sheriff come to the baseball game")
input("")
print("To stop people from stealing bases")